# src/train.py
import pandas as pd
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def main():
    # Read local csv generated by data pipeline
    df = pd.read_csv("data/clean_data.csv")

    # Split features and target, change "target" to your actual label column name
    X = df.drop("target", axis=1)
    y = df["target"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Train logistic regression model
    model = LogisticRegression(max_iter=200)
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Model Accuracy: {acc:.4f}")

    # Save model to src/model.joblib
    joblib.dump(model, "src/model.joblib")
    print("Model saved successfully to src/model.joblib")

if __name__ == "__main__":
    main()
